#!/bin/sh

if [[ $1 == upgrade ]]; then
    /bin/launchctl unload /Library/LaunchDaemons/com.openssh.sshd.plist
    /bin/launchctl load /Library/LaunchDaemons/com.openssh.sshd.plist
fi

if [[ $1 == install ]]; then
    /bin/launchctl load -w /Library/LaunchDaemons/com.openssh.sshd.plist
fi

exit 0
