#!/bin/bash
shopt -s extglob

if [[ $# -gt 1 && $1 == configure ]]; then
    if [[ $2 == 316s-5 ]]; then
        rm -f ~mobile/Library/Preferences/com.googlecode.mobileterminal.plist
    fi
fi

exit 0
