#!/bin/bash
LLVMPROGS="ar as bcanalyzer cxxdump cxxfilt diff dlltool dsymutil dwarfdump nm objdump pdbutil profdata ranlib readelf readobj size split strings"

case "$1" in
    configure)
	for prog in ${LLVMPROGS}; do
	    update-alternatives --quiet --install /usr/bin/${prog} ${prog} /usr/bin/llvm-${prog} 50
	done
	update-alternatives --quiet --install /usr/bin/gcc gcc /usr/bin/clang 50
	update-alternatives --quiet --install /usr/bin/cpp cpp /usr/bin/clang-cpp 50
	update-alternatives --quiet --install /usr/bin/g++ g++ /usr/bin/clang++ 50
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
