#!/bin/sh

if [[ $1 == upgrade ]]; then
    /bin/launchctl unload /System/Library/LaunchDaemons/com.saurik.afpd.dns-sd.plist
    /bin/launchctl unload /System/Library/LaunchDaemons/net.sourceforge.netatalk.afpd.plist
fi

if [[ $1 == install || $1 == upgrade ]]; then
    /bin/launchctl load /System/Library/LaunchDaemons/com.saurik.afpd.dns-sd.plist
    /bin/launchctl load /System/Library/LaunchDaemons/net.sourceforge.netatalk.afpd.plist
fi

exit 0
