#!/bin/zsh

set -e

if [ ! -e /bin/sh ]; then
    ln -s zsh /bin/sh
fi

case "$1" in
    abort-remove|configure)
        dpkg-divert --quiet --local --divert /bin/sh.distrib /bin/sh
        update-alternatives --quiet --install /bin/sh sh /bin/zsh 60 || true
        ;;
    *)
        exit 0
        ;;
esac
