#!/bin/zsh

set -e

case "$1" in
    upgrade)
  ;;

    remove|deconfigure)
      update-alternatives --quiet --remove sh /bin/zsh
      dpkg-divert --quiet --remove /bin/sh
      if [ ! -e /bin/sh ]; then
          echo There would be no shell!
          ln -s zsh /bin/sh
          exit 1
      fi
  ;;

    failed-upgrade)
  ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
  ;;
esac
