diff -Naur lua-5.3.5/Makefile lua-5.3.5+iPhone/Makefile
--- lua-5.3.5/Makefile	2016-12-20 08:26:08.000000000 -0800
+++ lua-5.3.5+iPhone/Makefile	2019-08-29 18:06:39.000000000 -0700
@@ -10,7 +10,8 @@
 # so take care if INSTALL_TOP is not an absolute path. See the local target.
 # You may want to make INSTALL_LMOD and INSTALL_CMOD consistent with
 # LUA_ROOT, LUA_LDIR, and LUA_CDIR in luaconf.h.
-INSTALL_TOP= /usr/local
+PREFIX= /usr/local
+INSTALL_TOP?= $(DESTDIR)/$(PREFIX)
 INSTALL_BIN= $(INSTALL_TOP)/bin
 INSTALL_INC= $(INSTALL_TOP)/include
 INSTALL_LIB= $(INSTALL_TOP)/lib
diff -Naur lua-5.3.5/src/Makefile lua-5.3.5+iPhone/src/Makefile
--- lua-5.3.5/src/Makefile	2018-06-25 10:46:36.000000000 -0700
+++ lua-5.3.5+iPhone/src/Makefile	2019-08-29 17:31:47.000000000 -0700
@@ -6,13 +6,10 @@
 # Your platform. See PLATS for possible values.
 PLAT= none
 
-CC= gcc -std=gnu99
 CFLAGS= -O2 -Wall -Wextra -DLUA_COMPAT_5_2 $(SYSCFLAGS) $(MYCFLAGS)
 LDFLAGS= $(SYSLDFLAGS) $(MYLDFLAGS)
 LIBS= -lm $(SYSLIBS) $(MYLIBS)
 
-AR= ar rcu
-RANLIB= ranlib
 RM= rm -f
 
 SYSCFLAGS=
